from sensorlab.constants import COULOMB_CONSTANT
from sensorlab.physics.geometry import ElectricFieldVector, Point3D
from .point_charge import PointCharge
from collections.abc import Iterable


def electric_field(
    source: PointCharge | Iterable[PointCharge],
    point: Point3D,
) -> ElectricFieldVector:
    """
    Electric field generated by a point charge
    at an arbitrary point in space.
    """

    if isinstance(source, PointCharge):
        return _electric_field_single(source, point)
    
    field = ElectricFieldVector(0.0, 0.0, 0.0, )

    count = 0

    for charge in source:
        try:
            field += electric_field(
                charge,
                point,
            )
            count += 1
        except ValueError:
            continue

    if count == 0:
        raise ValueError("Charge collection cannot be empty.")

    return field


def _electric_field_single(
    source: PointCharge,
    point: Point3D,
) -> ElectricFieldVector:
    direction, distance = source.position.direction_to(
        point
    )

    magnitude = (
        COULOMB_CONSTANT
        * source.charge.value
        / distance.value**2
    )

    vector = direction * magnitude
    return vector.cast(ElectricFieldVector)