from sensorlab.constants import COULOMB_CONSTANT
from sensorlab.physics.geometry import Point3D
from sensorlab.physics.quantities.electrical import Potential
from .point_charge import PointCharge
from collections.abc import Iterable


def electric_potential(
    source: PointCharge | Iterable[PointCharge],
    point: Point3D,
) -> Potential:
    """
    Electric potential generated by a point charge
    at an arbitrary point in space.

    This function implements the analytical solution for
    the electrostatic potential of a point charge.

    Notes
    -----
    V = k q / r

    The potential is referenced to infinity, where V = 0.
    """

    if isinstance(source, PointCharge):
        return _electric_potential_single(source, point)
    
    potential = 0.0
    count = 0

    for charge in source:
        try:
            potential += electric_potential(charge, point).value
            count += 1
        except ValueError:
            continue

    if count == 0:
        raise ValueError("Charge collection cannot be empty.")

    return Potential(potential)
    

def _electric_potential_single(
    source: PointCharge,
    point: Point3D,
) -> Potential:
    _, distance = source.position.direction_to(point)

    potential = (
        COULOMB_CONSTANT
        * source.charge.value
        / distance.value
    )

    return Potential(potential)